### ISSUE TITLE
synthesis time

### ISSUE THREAD

**Issue by DLZML001** [npuichigo/waveglow#2]
How long does it take to synthesise 1 second of audio? Is is like the paper,  faster than realtime?

**Comment by npuichigo** [comment]
The paper says that WaveGlow is slightly faster than Parallel WaveNet. But I think use gpu for inference is necessary to make it faster than the real time. After all, the model uses 96 (12 * 8) layers of WaveNet blocks during the forward pass.

**Comment by DLZML001** [comment]
ok thanks. On GPU it is synthesizing faster than realtime!
