### ISSUE TITLE
Undefined name: Where is _GetFileAndLine() defined?

### ISSUE THREAD

**Issue by cclauss** [npuichigo/waveglow#4]
https://github.com/npuichigo/waveglow/search?q=_GetFileAndLine

[flake8](http://flake8.pycqa.org) testing of https://github.com/npuichigo/waveglow on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./waveglow/logging.py:144:38: F821 undefined name '_GetFileAndLine'
    count = _GetNextLogCountPerToken(_GetFileAndLine())
                                     ^
./waveglow/logging.py:157:38: F821 undefined name '_GetFileAndLine'
    count = _GetNextLogCountPerToken(_GetFileAndLine())
                                     ^
2     F821 undefined name '_GetFileAndLine'
2
```

**Comment by npuichigo** [comment]
Oh, the logging file is modified from tensorflow, and it's my fault to omit something. Thank you for reminding me of that.
