### ISSUE TITLE
How to choose upsampling rte for conditioning?

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [npuichigo/waveglow#7]
@npuichigo 

I have local conditioning of following shape 1 X 1000 X 50 (for 1 sec) with input speech of 16k sampling rate. Can you recommend, which up sampling factor I should choose ? and How to estimate up sampling factor ?
Thanks

**Comment by npuichigo** [comment]
@ajinkyakulkarni14 - If the frame rate of your local condition is 1000hz, then the upsampling factor should be 16khz / 1khz = 16. For another example, if you use 5ms frames as local condition, then the upsampling factor would be 16khz * 5ms = 80. I use 200 for 12.5ms mel spectrograms by default, so I think your should adjust the transposed convolution layers to meet your requirements.

**Comment by ajinkyakulkarni14** [comment]
Thank you for the reply :)

**Comment by ajinkyakulkarni14** [comment]
@npuichigo ! Also, I would like to know how you set the squeeze factor on local conditioning ? 

Also, I have question, if I add nn.Embedding in Upsampling model, do I have to calculate the log Det of it ?

Regards
Ajinkya

**Comment by npuichigo** [comment]
@ajinkyakulkarni14 After upsampling of local condition, the frame rate of your audio and your local condition should be the same. So I think it's suitable to use the same squeeze factor of the audio samples, or maybe you can reduce both the upsampling factor and the squeeze factor.

Local condition doesn't affect the form of probability transform, so you can add embeddings without having to calculate the log det of it.

**Comment by ajinkyakulkarni14** [comment]
@npuichigo  Thanks alot for the answer ! 

Ajinkya Kulkarni
