### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by WangYizhang01** [npuichigo/waveglow#8]
你好，按照该仓库REDEME中的介绍，索引到tactron中数据处理的方法，但是好像数据命名问题是不一致的，也许是tactron中数据处理的部分更新了。
请问有没有其他数据预处理的模块。或者提供下数据集样式，谢谢！

**Comment by WangYizhang01** [comment]
@npuichigo @ss18

**Comment by npuichigo** [comment]
提取特征之后保证wav和npy对应就行，不一致的话rename一下

**Comment by WangYizhang01** [comment]
好的，已解决，感谢！
